version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Prepare Git
          command: |
            git config --global user.email "yusufh@protonmail.com"
            git config --global user.name "Yusuf CircleCI"
      - run:
          name: Install NPM packages
          command: npm install
      - run:
          name: Create Static Site
          command: node create-static-site.js
