version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    environment:
      TZ: "/usr/share/zoneinfo/Australia/Sydney"
    steps:
      - add_ssh_keys:
         fingerprints:
           - "b8:ea:07:84:3b:71:1a:9f:fd:b3:43:be:71:51:92:36"
      - checkout
      - run:
          name: Prepare Git
          command: |
            git config --global user.email "yusufh@protonmail.com"
            git config --global user.name "CircleCI"
      - run:
          name: Install NPM packages
          command: npm install
      - run:
          name: Create Static Site
          command: node create-static-site.js
